// eslint-disable-next-line import/no-anonymous-default-export
export default {
  REQUESTING: "REQUESTING",
  REQUEST_SUCCESS: "REQUEST_SUCCESS",
  REQUEST_FAILURE: "REQUEST_FAILURE",

  SET_CURRENT_ORG: "SET_CURRENT_ORG",

  SET_ORG: "SET_ORG",
  UPDATE_ORG: "UPDATE_ORG",

  ADD_EMPLOYEE: "ADD_EMPLOYEE",
  UPDATE_EMPLOYEE: "UPDATE_EMPLOYEE",
  DELETE_EMPLOYEE: "DELETE_EMPLOYEE",

  ADD_DEPARTMENT: "ADD_DEPARTMENT",
  UPDATE_DEPARTMENT: "UPDATE_DEPARTMENT",
  DELETE_DEPARTMENT: "DELETE_DEPARTMENT",

  ADD_POSITION: "ADD_POSITION",
  UPDATE_POSITION: "UPDATE_POSITION",
  DELETE_POSITION: "DELETE_POSITION",

  UPDATE_ATTENDANCE_POLICY: "UPDATE_ATTENDANCE_POLICY",
  RESET_ATTENDANCE_POLICY: "RESET_ATTENDANCE_POLICY",

  ADD_LEAVE_TYPE: "ADD_LEAVE_TYPE",
  UPDATE_LEAVE_TYPE: "UPDATE_LEAVE_TYPE",
  DELETE_LEAVE_TYPE: "DELETE_LEAVE_TYPE",

  ADD_HOLIDAY: "ADD_HOLIDAY",
  UPDATE_HOLIDAY: "UPDATE_HOLIDAY",
  DELETE_HOLIDAY: "DELETE_HOLIDAY",
};
