/** UI permission keys — keep in sync with packages/shared/permissions.js */
export const PERMISSIONS = Object.freeze({
  USERS_READ: "users:read",
  USERS_WRITE: "users:write",
  USERS_DELETE: "users:delete",
  EMPLOYEES_READ: "employees:read",
  EMPLOYEES_WRITE: "employees:write",
  EMPLOYEES_DELETE: "employees:delete",
  EMPLOYEES_IMPORT: "employees:import",
  EMPLOYEES_EXPORT: "employees:export",
  ORG_READ: "org:read",
  ORG_WRITE: "org:write",
  ORG_ADMIN: "org:admin",
  ATTENDANCE_READ: "attendance:read",
  ATTENDANCE_WRITE: "attendance:write",
  ATTENDANCE_APPROVE: "attendance:approve",
  LEAVES_READ: "leaves:read",
  LEAVES_WRITE: "leaves:write",
  LEAVES_APPROVE: "leaves:approve",
  PAYROLL_READ: "payroll:read",
  PAYROLL_WRITE: "payroll:write",
  PAYROLL_APPROVE: "payroll:approve",
  PAYROLL_GENERATE: "payroll:generate",
  REPORTS_READ: "reports:read",
  REPORTS_SCHEDULE: "reports:schedule",
  ANALYTICS_READ: "analytics:read",
  AUDIT_READ: "audit:read",
  SETTINGS_READ: "settings:read",
  SETTINGS_WRITE: "settings:write",
  DOCUMENTS_READ: "documents:read",
  DOCUMENTS_WRITE: "documents:write",
  ESS_ACCESS: "ess:access",
  ANNOUNCEMENTS_READ: "announcements:read",
  ANNOUNCEMENTS_WRITE: "announcements:write",
  SHIFTS_READ: "shifts:read",
  SHIFTS_WRITE: "shifts:write",
  WORKFLOWS_READ: "workflows:read",
  WORKFLOWS_WRITE: "workflows:write",
  WORKFLOWS_APPROVE: "workflows:approve",
  RECRUITMENT_READ: "recruitment:read",
  RECRUITMENT_WRITE: "recruitment:write",
  ONBOARDING_READ: "onboarding:read",
  ONBOARDING_WRITE: "onboarding:write",
  OFFBOARDING_READ: "offboarding:read",
  OFFBOARDING_WRITE: "offboarding:write",
  BENEFITS_READ: "benefits:read",
  BENEFITS_WRITE: "benefits:write",
  EXPENSES_READ: "expenses:read",
  EXPENSES_WRITE: "expenses:write",
  PERFORMANCE_READ: "performance:read",
  PERFORMANCE_WRITE: "performance:write",
  TRAINING_READ: "training:read",
  TRAINING_WRITE: "training:write",
});

export const ALL_PERMISSIONS = Object.freeze([...new Set(Object.values(PERMISSIONS))]);
export default PERMISSIONS;
